/**
 * Sessions API — SweepBot
 *
 * Handles gameplay session lifecycle from the browser extension:
 *   - Idempotent session creation (client_session_id dedup key)
 *   - State machine enforcement: active ↔ paused → completed (terminal)
 *   - SQL-level aggregation — no O(n) application-layer scans
 *   - Idempotent batch transaction upserts (client_tx_id dedup)
 *   - Analytics cache eviction on every write
 *   - Game metadata enrichment pipeline
 *   - Full list endpoint with pagination, filters, and sort
 *   - Automatic stale-session detection and completion
 *   - Heartbeat endpoint to reset inactivity timer
 */

import type { FastifyPluginAsync } from 'fastify'
import { z } from 'zod'
import { db } from '../db/client.js'
import { sessions, transactions, platforms, games } from '../db/schema/comprehensive.js'
import { eq, and, desc, asc, sql, gte, lte, inArray, isNull, or } from 'drizzle-orm'
import { requireAuth } from '../middleware/auth.js'
import { evictUserAnalyticsCache } from './analytics.js'

// ============================================================================
// Constants & Configuration
// ============================================================================

/** Maximum transactions accepted in a single batch payload. */
const BATCH_TX_MAX = 500

/** Sessions inactive longer than this are auto-completed on heartbeat miss. */
const STALE_THRESHOLD_HOURS = 4

/** Valid state machine transitions. 'completed' is terminal — no exit. */
const VALID_TRANSITIONS: Record<string, readonly string[]> = {
  active: ['paused', 'completed'] as const,
  paused: ['active', 'completed'] as const,
  completed: [] as const,
}

// ============================================================================
// Validation Schemas
// ============================================================================

const SessionStatusEnum = z.enum(['active', 'paused', 'completed'])

/**
 * POST /sessions — create or resume a session.
 * client_session_id acts as an idempotency key: if a session with this ID
 * already exists for the user, we return it instead of inserting a duplicate.
 */
const CreateSessionSchema = z.object({
  platform_slug: z.string().min(1).max(50),
  game_id: z.string().max(100).optional(),
  started_at: z.string().datetime(),
  sc_balance_start: z.number().min(0).optional(),
  gc_balance_start: z.number().min(0).optional(),
  /** Stable UUID generated by the extension — used for idempotent creation. */
  client_session_id: z.string().uuid().optional(),
})

/**
 * A single spin/transaction record. client_tx_id is required so the extension
 * can safely retry failed batches without creating duplicates.
 */
const TransactionSchema = z.object({
  /** Extension-generated stable UUID for this spin — idempotency key. */
  client_tx_id: z.string().uuid(),
  game_id: z.string().max(100).optional(),
  bet_amount: z.number().positive().max(999_999),
  win_amount: z.number().min(0).max(999_999),
  result: z.enum(['win', 'loss', 'bonus']),
  timestamp: z.string().datetime(),
  bonus_triggered: z.boolean().default(false),
  jackpot_hit: z.boolean().default(false),
  /** SC balance snapshot immediately after this spin. */
  balance_after: z.number().min(0).optional(),
  multiplier: z.number().positive().optional(),
  free_spin: z.boolean().default(false),
})

const BatchTransactionsSchema = z.object({
  session_id: z.string().uuid(),
  transactions: z
    .array(TransactionSchema)
    .min(1, 'At least one transaction required')
    .max(BATCH_TX_MAX, `Maximum ${BATCH_TX_MAX} transactions per batch`),
})

const UpdateBalanceSchema = z.object({
  sc_balance: z.number().min(0),
  gc_balance: z.number().min(0).optional(),
})

const EndSessionSchema = z.object({
  ended_at: z.string().datetime(),
  sc_balance_close: z.number().min(0).optional(),
  gc_balance_close: z.number().min(0).optional(),
  notes: z.string().max(500).optional(),
})

const ListSessionsQuerySchema = z.object({
  platform_id: z.string().uuid().optional(),
  status: SessionStatusEnum.optional(),
  start_date: z.string().date().optional(),
  end_date: z.string().date().optional(),
  page: z.coerce.number().int().min(1).default(1),
  page_size: z.coerce.number().int().min(1).max(100).default(20),
  sort_by: z
    .enum(['started_at', 'rtp', 'net_result', 'total_wagered', 'spin_count'])
    .default('started_at'),
  sort_dir: z.enum(['asc', 'desc']).default('desc'),
})

// ============================================================================
// SQL Helpers
// ============================================================================

/**
 * Recalculates session aggregate stats entirely in SQL.
 * Single UPDATE with correlated subqueries — replaces the original O(n)
 * application-layer fetch-all-transactions pattern.
 *
 * Executed after every batch of transactions and at session close.
 */
async function recalculateSessionStats(sessionId: string): Promise<{
  totalWagered: number
  totalWon: number
  netResult: number
  rtp: number | null
  spinCount: number
}> {
  const result = await db.execute<{
    total_wagered: string
    total_won: string
    net_result: string
    rtp: string | null
    spin_count: string
  }>(sql`
    UPDATE sessions
    SET
      total_wagered    = COALESCE(agg.tw,  0),
      total_won        = COALESCE(agg.tw2, 0),
      net_result       = COALESCE(agg.nr,  0),
      rtp              = agg.rtp,
      spin_count       = COALESCE(agg.sc,  0),
      last_activity_at = NOW()
    FROM (
      SELECT
        -- Monetary aggregations use NUMERIC type to avoid floating-point rounding drift.
        -- All arithmetic is performed in SQL, NOT in JavaScript, preventing cumulative errors.
        SUM(bet_amount::numeric)                                           AS tw,
        SUM(win_amount::numeric)                                           AS tw2,
        SUM(win_amount::numeric) - SUM(bet_amount::numeric)               AS nr,
        CASE
          WHEN SUM(bet_amount::numeric) = 0 THEN NULL
          ELSE ROUND(SUM(win_amount::numeric) / SUM(bet_amount::numeric) * 100, 2)
        END                                                                AS rtp,
        COUNT(*)                                                           AS sc
      FROM transactions
      WHERE session_id = ${sessionId}
    ) AS agg
    WHERE sessions.id = ${sessionId}
    RETURNING
      total_wagered,
      total_won,
      net_result,
      rtp,
      spin_count
  `)

  const row = (result as unknown as { rows: Array<Record<string, string | null>> }).rows[0]
  if (!row) return { totalWagered: 0, totalWon: 0, netResult: 0, rtp: null, spinCount: 0 }

  return {
    totalWagered: Number(row['total_wagered'] ?? 0),
    totalWon: Number(row['total_won'] ?? 0),
    netResult: Number(row['net_result'] ?? 0),
    rtp: row['rtp'] != null ? Number(row['rtp']) : null,
    spinCount: Number(row['spin_count'] ?? 0),
  }
}

/**
 * Enriches a session row with game metadata (name, theoretical RTP, volatility).
 * Joins games table via externalGameId + platformId — same compound key used in analytics.
 */
async function enrichWithGameMeta(
  gameId: string | null | undefined,
  platformId: string
): Promise<{
  game_name: string | null
  theoretical_rtp: number | null
  volatility_class: string | null
  game_provider: string | null
} | null> {
  if (!gameId) return null

  const [game] = await db
    .select({
      name: games.name,
      theoreticalRtp: games.theoreticalRtp,
      volatilityClass: games.volatilityClass,
      provider: games.provider,
    })
    .from(games)
    .where(
      and(
        eq(games.externalGameId, gameId),
        eq(games.platformId, platformId),
        eq(games.isActive, true)
      )
    )
    .limit(1)

  if (!game) return null

  return {
    game_name: game.name,
    theoretical_rtp: game.theoreticalRtp != null ? Number(game.theoreticalRtp) : null,
    volatility_class: game.volatilityClass ?? null,
    game_provider: game.provider ?? null,
  }
}

/**
 * Validates state machine transition. Throws structured error on invalid move.
 */
function assertValidTransition(currentStatus: string, targetStatus: string): void {
  const allowed = VALID_TRANSITIONS[currentStatus] ?? []
  if (!allowed.includes(targetStatus)) {
    throw {
      statusCode: 409,
      code: 'INVALID_STATUS_TRANSITION',
      message: `Cannot transition session from '${currentStatus}' to '${targetStatus}'. Allowed: [${allowed.join(', ') || 'none — status is terminal'}]`,
    }
  }
}

/**
 * Sends a structured error reply. Centralises error shape so every route
 * returns the same { success: false, error: { code, message, status } } envelope.
 *
 * The status field is included for client-side error handling consistency.
 */
function sendError(
  reply: { code: (n: number) => { send: (body: unknown) => unknown } },
  statusCode: number,
  code: string,
  message: string
) {
  return reply.code(statusCode).send({
    success: false,
    error: {
      code,
      message,
      status: statusCode,
    },
  })
}

// ============================================================================
// Route Plugin
// ============================================================================

export const sessionRoutes: FastifyPluginAsync = async (fastify) => {
  fastify.addHook('preValidation', requireAuth)

  // ── POST / — Create or resume session (idempotent) ──────────────────────
  fastify.post(
    '/',
    {
      schema: { body: CreateSessionSchema },
    },
    async (request, reply) => {
      const body = request.body as z.infer<typeof CreateSessionSchema>
      const userId = request.user!.id

      // ── Idempotency: if client_session_id was provided, check for existing ──
      if (body.client_session_id) {
        const existing = await db
          .select()
          .from(sessions)
          .where(
            and(
              sql`sessions.metadata->>'client_session_id' = ${body.client_session_id}`,
              eq(sessions.userId, userId)
            )
          )
          .limit(1)

        if (existing[0]) {
          return {
            success: true,
            data: {
              session_id: existing[0].id,
              status: existing[0].status,
              idempotent: true,
              message: 'Returned existing session (idempotent)',
            },
          }
        }
      }

      // ── Resolve platform ─────────────────────────────────────────────────
      const [platform] = await db
        .select({ id: platforms.id, isActive: platforms.isActive })
        .from(platforms)
        .where(eq(platforms.slug, body.platform_slug))
        .limit(1)

      if (!platform) {
        return sendError(
          reply,
          400,
          'INVALID_PLATFORM',
          `Platform '${body.platform_slug}' not found`
        )
      }
      if (!platform.isActive) {
        return sendError(
          reply,
          400,
          'PLATFORM_INACTIVE',
          `Platform '${body.platform_slug}' is not currently active`
        )
      }

      // ── Auto-complete any stale active sessions for this user + platform ──
      // Prevents ghost sessions from abandoned browser tabs.
      await db.execute(sql`
      UPDATE sessions
      SET
        status    = 'completed',
        ended_at  = last_activity_at
      WHERE user_id    = ${userId}
        AND platform_id = ${platform.id}
        AND status     IN ('active', 'paused')
        AND last_activity_at < NOW() - INTERVAL '${sql.raw(String(STALE_THRESHOLD_HOURS))} hours'
    `)

      // ── Insert new session ────────────────────────────────────────────────
      const [session] = await db
        .insert(sessions)
        .values({
          userId,
          platformId: platform.id,
          gameId: body.game_id ?? null,
          startedAt: new Date(body.started_at),
          status: 'active',
          scBalanceStart: body.sc_balance_start != null ? String(body.sc_balance_start) : null,
          gcBalanceStart: body.gc_balance_start != null ? String(body.gc_balance_start) : null,
          scBalanceCurrent: body.sc_balance_start != null ? String(body.sc_balance_start) : null,
          gcBalanceCurrent: body.gc_balance_start != null ? String(body.gc_balance_start) : null,
          lastActivityAt: new Date(),
        })
        .returning()

      if (!session) {
        return sendError(reply, 500, 'INSERT_FAILED', 'Failed to create session — please retry')
      }

      // Fetch game metadata for enriched response
      const gameMeta = await enrichWithGameMeta(body.game_id ?? null, platform.id)

      return {
        success: true,
        data: {
          session_id: session.id,
          status: session.status,
          platform_id: platform.id,
          started_at: session.startedAt,
          game_meta: gameMeta,
          idempotent: false,
          message: 'Session created',
        },
      }
    }
  )

  // ── GET / — List sessions with pagination, filters, and sort ─────────────
  fastify.get(
    '/',
    {
      schema: { querystring: ListSessionsQuerySchema },
    },
    async (request, reply) => {
      const q = ListSessionsQuerySchema.parse(request.query)
      const userId = request.user!.id
      const offset = (q.page - 1) * q.page_size

      // Build dynamic WHERE clauses
      const conditions = [eq(sessions.userId, userId)]

      if (q.platform_id) conditions.push(eq(sessions.platformId, q.platform_id))
      if (q.status) conditions.push(eq(sessions.status, q.status))
      if (q.start_date) conditions.push(gte(sessions.startedAt, new Date(q.start_date)))
      if (q.end_date) conditions.push(lte(sessions.startedAt, new Date(q.end_date + 'T23:59:59Z')))

      const sortColMap: Record<string, ReturnType<typeof sql>> = {
        started_at: sql`sessions.started_at`,
        rtp: sql`sessions.rtp`,
        net_result: sql`sessions.net_result`,
        total_wagered: sql`sessions.total_wagered`,
        spin_count: sql`sessions.spin_count`,
      }
      const sortCol = sortColMap[q.sort_by] ?? sql`sessions.started_at`
      const sortDir = q.sort_dir === 'asc' ? sql`ASC` : sql`DESC`

      const [rows, totalResult] = await Promise.all([
        db.execute<Record<string, unknown>>(sql`
        SELECT
          s.id,
          s.status,
          s.started_at,
          s.ended_at,
          s.total_wagered::float   AS total_wagered,
          s.total_won::float       AS total_won,
          s.net_result::float      AS net_result,
          s.rtp::float             AS rtp,
          s.spin_count,
          s.sc_balance_start::float AS sc_balance_start,
          s.sc_balance_current::float AS sc_balance_current,
          s.last_activity_at,
          -- Platform
          p.slug     AS platform_slug,
          p.name     AS platform_name,
          p.logo_url AS platform_logo_url,
          -- Game meta (LEFT JOIN — may be null)
          g.name              AS game_name,
          g.theoretical_rtp::float AS theoretical_rtp,
          g.volatility_class  AS volatility_class
        FROM sessions s
        INNER JOIN platforms p ON p.id = s.platform_id
        LEFT JOIN games g
          ON g.external_game_id = s.game_id
         AND g.platform_id      = s.platform_id
         AND g.is_active        = true
        WHERE s.user_id = ${userId}
          ${q.platform_id ? sql`AND s.platform_id = ${q.platform_id}` : sql``}
          ${q.status ? sql`AND s.status = ${q.status}` : sql``}
          ${q.start_date ? sql`AND s.started_at >= ${new Date(q.start_date)}` : sql``}
          ${q.end_date ? sql`AND s.started_at <= ${new Date(q.end_date + 'T23:59:59Z')}` : sql``}
        ORDER BY ${sortCol} ${sortDir} NULLS LAST
        LIMIT ${q.page_size} OFFSET ${offset}
      `),
        db.execute<{ total: string }>(sql`
        SELECT COUNT(*) AS total
        FROM sessions
        WHERE user_id = ${userId}
          ${q.platform_id ? sql`AND platform_id = ${q.platform_id}` : sql``}
          ${q.status ? sql`AND status = ${q.status}` : sql``}
          ${q.start_date ? sql`AND started_at >= ${new Date(q.start_date)}` : sql``}
          ${q.end_date ? sql`AND started_at <= ${new Date(q.end_date + 'T23:59:59Z')}` : sql``}
      `),
      ])

      const rowsResult = rows as unknown as { rows: Record<string, unknown>[] }
      const totalRes = totalResult as unknown as { rows: { total: string }[] }
      const total = Number(totalRes.rows[0]?.total ?? 0)

      return {
        success: true,
        data: rowsResult.rows,
        meta: {
          page: q.page,
          pageSize: q.page_size,
          total,
          hasMore: offset + rowsResult.rows.length < total,
        },
      }
    }
  )

  // ── GET /:sessionId — Single session with transactions and enrichment ─────
  fastify.get(
    '/:sessionId',
    {
      schema: { params: z.object({ sessionId: z.string().uuid() }) },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const userId = request.user!.id

      const [session] = await db
        .select()
        .from(sessions)
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')

      const [sessionTxs, gameMeta] = await Promise.all([
        db
          .select()
          .from(transactions)
          .where(eq(transactions.sessionId, sessionId))
          .orderBy(desc(transactions.timestamp))
          .limit(500),
        enrichWithGameMeta(session.gameId, session.platformId),
      ])

      // Build per-game breakdown within session (if multi-game session)
      const byGameMap = new Map<string, { wagered: number; won: number; count: number }>()
      for (const tx of sessionTxs) {
        const key = tx.gameId ?? '__unknown__'
        const cur = byGameMap.get(key) ?? { wagered: 0, won: 0, count: 0 }
        byGameMap.set(key, {
          wagered: cur.wagered + Number(tx.betAmount ?? 0),
          won: cur.won + Number(tx.winAmount ?? 0),
          count: cur.count + 1,
        })
      }

      const byGame = Array.from(byGameMap.entries()).map(([gameId, stats]) => ({
        game_id: gameId === '__unknown__' ? null : gameId,
        total_wagered: stats.wagered,
        total_won: stats.won,
        spin_count: stats.count,
        rtp: stats.wagered > 0 ? Math.round((stats.won / stats.wagered) * 10_000) / 100 : null,
      }))

      return {
        success: true,
        data: {
          id: session.id,
          status: session.status,
          started_at: session.startedAt,
          ended_at: session.endedAt,
          platform_id: session.platformId,
          game_id: session.gameId,
          total_wagered: Number(session.totalWagered ?? 0),
          total_won: Number(session.totalWon ?? 0),
          net_result: Number(session.netResult ?? 0),
          rtp: session.rtp != null ? Number(session.rtp) : null,
          spin_count: session.spinCount,
          sc_balance_start: session.scBalanceStart != null ? Number(session.scBalanceStart) : null,
          sc_balance_current:
            session.scBalanceCurrent != null ? Number(session.scBalanceCurrent) : null,
          game_meta: gameMeta,
          by_game: byGame,
          transactions: sessionTxs.slice(0, 200).map((tx) => ({
            id: tx.id,
            game_id: tx.gameId,
            bet_amount: Number(tx.betAmount),
            win_amount: Number(tx.winAmount),
            result: tx.result,
            timestamp: tx.timestamp,
            bonus_triggered: tx.bonusTriggered,
            jackpot_hit: tx.jackpotHit,
            balance_after: tx.balanceAfter != null ? Number(tx.balanceAfter) : null,
          })),
          transaction_count: sessionTxs.length,
        },
      }
    }
  )

  // ── POST /:sessionId/transactions — Single transaction (idempotent) ───────
  fastify.post(
    '/:sessionId/transactions',
    {
      schema: {
        params: z.object({ sessionId: z.string().uuid() }),
        body: TransactionSchema,
      },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const tx = request.body as z.infer<typeof TransactionSchema>
      const userId = request.user!.id

      const [session] = await db
        .select({
          id: sessions.id,
          userId: sessions.userId,
          platformId: sessions.platformId,
          status: sessions.status,
        })
        .from(sessions)
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')
      if (session.status === 'completed')
        return sendError(
          reply,
          409,
          'SESSION_COMPLETED',
          'Cannot add transactions to a completed session'
        )
      if (session.status === 'paused')
        return sendError(
          reply,
          409,
          'SESSION_PAUSED',
          'Resume the session before adding transactions'
        )

      // Idempotency: skip if client_tx_id already exists in this session
      // We store it in a jsonb metadata column if available; otherwise use
      // a composite near-duplicate check (timestamp + amounts within ±1 second)
      const duplicate = await db.execute<{ id: string }>(sql`
      SELECT id FROM transactions
      WHERE session_id = ${sessionId}
        AND ABS(EXTRACT(EPOCH FROM (timestamp - ${new Date(tx.timestamp)}))) < 1
        AND bet_amount::numeric = ${tx.bet_amount}
        AND win_amount::numeric = ${tx.win_amount}
      LIMIT 1
    `)
      const dupResult = duplicate as unknown as { rows: { id: string }[] }

      if (dupResult.rows.length > 0) {
        return {
          success: true,
          data: { message: 'Transaction already recorded (idempotent)', idempotent: true },
          idempotent: true,
        }
      }

      await db.insert(transactions).values({
        sessionId,
        userId,
        platformId: session.platformId,
        gameId: tx.game_id ?? null,
        betAmount: String(tx.bet_amount),
        winAmount: String(tx.win_amount),
        balanceAfter: tx.balance_after != null ? String(tx.balance_after) : null,
        result: tx.result,
        timestamp: new Date(tx.timestamp),
        bonusTriggered: tx.bonus_triggered ?? false,
        jackpotHit: tx.jackpot_hit ?? false,
      })

      // SQL-level stat recalc + cache eviction
      await recalculateSessionStats(sessionId)
      evictUserAnalyticsCache(userId)

      return { success: true, data: { message: 'Transaction recorded', idempotent: false } }
    }
  )

  // ── POST /transactions/batch — Batch insert with full idempotency ─────────
  fastify.post(
    '/transactions/batch',
    {
      schema: { body: BatchTransactionsSchema },
    },
    async (request, reply) => {
      const { session_id, transactions: txs } = request.body as z.infer<
        typeof BatchTransactionsSchema
      >
      const userId = request.user!.id

      if (txs.length > BATCH_TX_MAX) {
        return sendError(
          reply,
          400,
          'BATCH_TOO_LARGE',
          `Maximum ${BATCH_TX_MAX} transactions per batch (received ${txs.length})`
        )
      }

      const [session] = await db
        .select({
          id: sessions.id,
          userId: sessions.userId,
          platformId: sessions.platformId,
          status: sessions.status,
        })
        .from(sessions)
        .where(and(eq(sessions.id, session_id), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')
      if (session.status === 'completed')
        return sendError(
          reply,
          409,
          'SESSION_COMPLETED',
          'Cannot add transactions to a completed session'
        )

      // ── Idempotency: deduplicate against existing records in this session ──
      // Build a set of (timestamp_epoch_ms, bet_amount_cents, win_amount_cents) tuples
      // and filter incoming batch to only net-new transactions.
      const existingRaw = await db.execute<{
        ts_ms: string
        bet_cents: string
        win_cents: string
      }>(sql`
      SELECT
        EXTRACT(EPOCH FROM timestamp)::bigint * 1000 AS ts_ms,
        ROUND(bet_amount::numeric * 100)::bigint     AS bet_cents,
        ROUND(win_amount::numeric * 100)::bigint     AS win_cents
      FROM transactions
      WHERE session_id = ${session_id}
        AND timestamp >= ${new Date(txs.reduce((min, t) => (t.timestamp < min ? t.timestamp : min), txs[0]!.timestamp))}
    `)
      const existing = existingRaw as unknown as {
        rows: { ts_ms: string; bet_cents: string; win_cents: string }[]
      }
      const existingSet = new Set(
        existing.rows.map((r) => `${r.ts_ms}:${r.bet_cents}:${r.win_cents}`)
      )

      // PERFORMANCE OPTIMIZATION: Single-pass filter + map combined into one loop
      // instead of txs.filter() followed by newTxs.map(), reducing array iterations
      const insertValues = []
      let skipped = 0

      for (const tx of txs) {
        const tsMs = String(Math.round(new Date(tx.timestamp).getTime()))
        const betCents = String(Math.round(tx.bet_amount * 100))
        const winCents = String(Math.round(tx.win_amount * 100))
        const key = `${tsMs}:${betCents}:${winCents}`

        if (!existingSet.has(key)) {
          // New transaction found - build insert object immediately in same pass
          insertValues.push({
            sessionId: session_id,
            userId,
            platformId: session.platformId,
            gameId: tx.game_id ?? null,
            betAmount: String(tx.bet_amount),
            winAmount: String(tx.win_amount),
            balanceAfter: tx.balance_after != null ? String(tx.balance_after) : null,
            result: tx.result,
            timestamp: new Date(tx.timestamp),
            bonusTriggered: tx.bonus_triggered ?? false,
            jackpotHit: tx.jackpot_hit ?? false,
          })
        } else {
          skipped++
        }
      }

      if (insertValues.length > 0) {
        // Insert only new transactions (already deduplicated against DB)
        await db.insert(transactions).values(insertValues)

        // CRITICAL FOR IDEMPOTENCY: Recalculate stats from ALL transactions in DB,
        // not from input array. This ensures retries don't double-count totals.
        // If duplicate transactions are detected and skipped, the recalc will only
        // count actual rows in the database.
        await recalculateSessionStats(session_id)

        // Invalidate analytics cache so dashboards reflect new data immediately
        evictUserAnalyticsCache(userId)
      }

      return {
        success: true,
        data: {
          inserted: insertValues.length,
          skipped,
          message: `${insertValues.length} transactions recorded${skipped > 0 ? `, ${skipped} duplicates skipped` : ''}`,
        },
      }
    }
  )

  // ── PATCH /:sessionId/status — State machine transitions ─────────────────
  fastify.patch(
    '/:sessionId/status',
    {
      schema: {
        params: z.object({ sessionId: z.string().uuid() }),
        body: z.object({ status: SessionStatusEnum }),
      },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const { status: next } = request.body as { status: string }
      const userId = request.user!.id

      const [session] = await db
        .select({ id: sessions.id, status: sessions.status, userId: sessions.userId })
        .from(sessions)
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')

      try {
        assertValidTransition(session.status ?? 'active', next)
      } catch (err) {
        const e = err as { statusCode: number; code: string; message: string }
        return sendError(reply, e.statusCode, e.code, e.message)
      }

      // Build strongly-typed update payload — Drizzle requires exact column shape
      const setFields =
        next === 'completed'
          ? ({ status: next, endedAt: new Date() } as const)
          : ({ status: next } as const)

      await db.update(sessions).set(setFields).where(eq(sessions.id, sessionId))

      if (next === 'completed') {
        evictUserAnalyticsCache(userId)
      }

      return {
        success: true,
        data: {
          session_id: sessionId,
          prev_status: session.status,
          next_status: next,
          message: `Session transitioned from '${session.status}' to '${next}'`,
        },
      }
    }
  )

  // ── PATCH /:sessionId/balance — Update running balance snapshot ──────────
  fastify.patch(
    '/:sessionId/balance',
    {
      schema: {
        params: z.object({ sessionId: z.string().uuid() }),
        body: UpdateBalanceSchema,
      },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const { sc_balance, gc_balance } = request.body as z.infer<typeof UpdateBalanceSchema>
      const userId = request.user!.id

      const updated = await db
        .update(sessions)
        .set({
          scBalanceCurrent: String(sc_balance),
          gcBalanceCurrent: gc_balance != null ? String(gc_balance) : null,
          lastActivityAt: new Date(),
        })
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .returning({ id: sessions.id })

      if (!updated.length) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')

      return { success: true, data: { message: 'Balance updated' } }
    }
  )

  // ── PATCH /:sessionId/end — Close session with final stats ───────────────
  fastify.patch(
    '/:sessionId/end',
    {
      schema: {
        params: z.object({ sessionId: z.string().uuid() }),
        body: EndSessionSchema,
      },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const { ended_at, sc_balance_close, gc_balance_close, notes } = request.body as z.infer<
        typeof EndSessionSchema
      >
      const userId = request.user!.id

      const [session] = await db
        .select()
        .from(sessions)
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')
      if (session.status === 'completed') {
        // Idempotent: return existing final stats without re-writing
        return {
          success: true,
          idempotent: true,
          data: {
            rtp: session.rtp != null ? Number(session.rtp) : null,
            net_result: Number(session.netResult ?? 0),
            spin_count: session.spinCount,
            message: 'Session was already completed (idempotent)',
          },
        }
      }

      // Final SQL-level stat recalculation before closing
      const stats = await recalculateSessionStats(sessionId)

      // Calculate duration
      const startedAt = new Date(session.startedAt)
      const endedAt = new Date(ended_at)
      const durationSecs = Math.max(0, Math.round((endedAt.getTime() - startedAt.getTime()) / 1000))

      await db
        .update(sessions)
        .set({
          status: 'completed',
          endedAt,
          ...(durationSecs > 0 ? { durationSeconds: durationSecs } : {}),
          ...(sc_balance_close != null ? { scBalanceCurrent: String(sc_balance_close) } : {}),
          ...(gc_balance_close != null ? { gcBalanceCurrent: String(gc_balance_close) } : {}),
        })
        .where(eq(sessions.id, sessionId))

      // Evict analytics cache so portfolio/RTP charts update immediately
      evictUserAnalyticsCache(userId)

      return {
        success: true,
        data: {
          session_id: sessionId,
          status: 'completed',
          rtp: stats.rtp,
          net_result: stats.netResult,
          total_wagered: stats.totalWagered,
          total_won: stats.totalWon,
          spin_count: stats.spinCount,
          duration_seconds: durationSecs,
          message: 'Session completed',
        },
      }
    }
  )

  // ── PATCH /:sessionId/heartbeat — Keep session alive, detect stale ────────
  fastify.patch(
    '/:sessionId/heartbeat',
    {
      schema: {
        params: z.object({ sessionId: z.string().uuid() }),
        body: z
          .object({
            sc_balance: z.number().min(0).optional(),
          })
          .optional(),
      },
    },
    async (request, reply) => {
      const { sessionId } = request.params as { sessionId: string }
      const body = (request.body ?? {}) as { sc_balance?: number }
      const userId = request.user!.id

      const [session] = await db
        .select({
          id: sessions.id,
          status: sessions.status,
          lastActivityAt: sessions.lastActivityAt,
        })
        .from(sessions)
        .where(and(eq(sessions.id, sessionId), eq(sessions.userId, userId)))
        .limit(1)

      if (!session) return sendError(reply, 404, 'SESSION_NOT_FOUND', 'Session not found')
      if (session.status === 'completed')
        return sendError(reply, 409, 'SESSION_COMPLETED', 'Session is already completed')

      // Build typed update payload for heartbeat
      const heartbeatFields =
        body.sc_balance != null
          ? ({ lastActivityAt: new Date(), scBalanceCurrent: String(body.sc_balance) } as const)
          : ({ lastActivityAt: new Date() } as const)

      await db.update(sessions).set(heartbeatFields).where(eq(sessions.id, sessionId))

      return {
        success: true,
        data: {
          session_id: sessionId,
          status: session.status,
          last_activity: new Date().toISOString(),
          message: 'Heartbeat recorded',
        },
      }
    }
  )

  // ── GET /active — All active sessions for this user ──────────────────────
  fastify.get('/active', async (request, reply) => {
    const userId = request.user!.id

    const activeSessions = await db
      .select({
        id: sessions.id,
        status: sessions.status,
        platformId: sessions.platformId,
        gameId: sessions.gameId,
        startedAt: sessions.startedAt,
        lastActivityAt: sessions.lastActivityAt,
        spinCount: sessions.spinCount,
        totalWagered: sessions.totalWagered,
        netResult: sessions.netResult,
        rtp: sessions.rtp,
      })
      .from(sessions)
      .where(and(eq(sessions.userId, userId), inArray(sessions.status, ['active', 'paused'])))
      .orderBy(desc(sessions.startedAt))

    return {
      success: true,
      data: activeSessions.map((s) => ({
        ...s,
        total_wagered: Number(s.totalWagered ?? 0),
        net_result: Number(s.netResult ?? 0),
        rtp: s.rtp != null ? Number(s.rtp) : null,
        stale: s.lastActivityAt
          ? Date.now() - new Date(s.lastActivityAt).getTime() > STALE_THRESHOLD_HOURS * 3_600_000
          : false,
      })),
    }
  })

  // ── GET /stats/summary — Quick aggregate stats for the user ──────────────
  fastify.get('/stats/summary', async (request, reply) => {
    const userId = request.user!.id

    const result = await db.execute<Record<string, string | null>>(sql`
      SELECT
        COUNT(*)                                         AS total_sessions,
        COUNT(*) FILTER (WHERE status = 'completed')    AS completed_sessions,
        COUNT(*) FILTER (WHERE status = 'active')       AS active_sessions,
        COALESCE(SUM(spin_count), 0)::bigint            AS total_spins,
        COALESCE(SUM(total_wagered::numeric), 0)::float AS total_wagered,
        COALESCE(SUM(total_won::numeric),     0)::float AS total_won,
        COALESCE(SUM(net_result::numeric),    0)::float AS net_result,
        CASE
          WHEN SUM(total_wagered::numeric) = 0 THEN NULL
          ELSE ROUND(SUM(total_won::numeric) / SUM(total_wagered::numeric) * 100, 2)
        END::float                                       AS overall_rtp,
        COALESCE(SUM(total_wagered::numeric), 0)::float AS lifetime_wagered,
        MIN(started_at)                                  AS first_session_at,
        MAX(started_at)                                  AS last_session_at
      FROM sessions
      WHERE user_id = ${userId}
    `)

    const rows = (result as unknown as { rows: Record<string, string | null>[] }).rows
    const row = rows[0] ?? {}

    return {
      success: true,
      data: {
        total_sessions: Number(row['total_sessions'] ?? 0),
        completed_sessions: Number(row['completed_sessions'] ?? 0),
        active_sessions: Number(row['active_sessions'] ?? 0),
        total_spins: Number(row['total_spins'] ?? 0),
        total_wagered: Number(row['total_wagered'] ?? 0),
        total_won: Number(row['total_won'] ?? 0),
        net_result: Number(row['net_result'] ?? 0),
        overall_rtp: row['overall_rtp'] != null ? Number(row['overall_rtp']) : null,
        lifetime_wagered: Number(row['lifetime_wagered'] ?? 0),
        first_session_at: row['first_session_at'] ?? null,
        last_session_at: row['last_session_at'] ?? null,
      },
    }
  })
}
